# Generated by Django 3.1.6 on 2021-03-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='filename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
